version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g yarn
      - yarn install
      - echo "Yarn installed!"

  build:
    commands:
      - echo "REACT_APP_MITTHELSINGBORG_IO=https://$API_DOMAIN/forms" > .env
      - CI=false npm run build
      - CRED=`aws sts assume-role --role-arn arn:aws:iam::$AWS_ACCOUNT_NBR:role/ServerlessDeployRole --role-session-name env-access`
      - AWS_ACCESS_KEY_ID=`node -pe 'JSON.parse(process.argv[1]).Credentials.AccessKeyId' "$CRED"`
      - AWS_SECRET_ACCESS_KEY=`node -pe 'JSON.parse(process.argv[1]).Credentials.SecretAccessKey' "$CRED"`
      - AWS_SESSION_TOKEN=`node -pe 'JSON.parse(process.argv[1]).Credentials.SessionToken' "$CRED"`
      - AWS_EXPIRATION=`node -pe 'JSON.parse(process.argv[1]).Credentials.Expiration' "$CRED"`
      - cd build
      - aws s3 sync . s3://$BUCKET_NAME --no-follow-symlinks
cache:
  paths:
    - node_modules/**/*
    - /usr/local/share/.config/yarn/**/*
    - /usr/local/share/.cache/yarn/v6/**/*
    - /root/.npm/**/*
