on: 
  push:
    branches:
    - master

jobs:
  build_and_s3_deploy:
    runs-on: ubuntu-latest
    name: Build and deploy to S3 bucket
    steps:
    - name: Checkout step
      uses: actions/checkout@master
    - name: Build step
      run: |
        npm install 
        npm run build
    - name: Sync to S3 bucket
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env: 
        AWS_S3_BUCKET: ${{ secrets.FORMBUILDER_DEV_AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.FORMBUILDER_DEV_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.FORMBUILDER_DEV_AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-north-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'build'      # optional: defaults to entire repository
        